name: dumiya_livreur_app
publish_to: none
description: Application livreur Dumiya compatible avec le module Odoo Dumiya Delivery Cashier V3.
version: 3.0.1+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  cookie_jar: ^4.0.8
  dio_cookie_manager: ^3.1.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  signature: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
